### ISSUE TITLE
Z raise before homing X or Y

### ISSUE THREAD

**Issue by Nemilad** [pinguinpfleger/ASWX1-FW-MOD#12]
When I press home X or Y on the menu Z goes up and then not goes down after homing. If I press home X and then home Y and repeat it just goes higher and higher. Because of that resume printing not working anymore, because after homing X and Y it start printing in midair. It wasn't happening on original firmware.
How I can fix that?

**Comment by Bodengriller** [comment]
With us (and some others too) the combination of the FW + TFT-FW offered here works.

You could try flashing both again, I can't imagine what else could have gone wrong.
