### ISSUE TITLE
[QUESTION] MBL funktioniert nicht - Mesh Daten werden nicht gespeichert

### ISSUE THREAD

**Issue by Hundsbuah** [pinguinpfleger/ASWX1-FW-MOD#14]
Servus zusammen, 

ich hab versucht bei der Source vom 1.2 Release Mesh Bed Leveling (MBL) zu aktivieren.
Folgendes hab ich aktiviert:

#define MESH_BED_LEVELING
#define RESTORE_LEVELING_AFTER_G28
#define G26_MESH_VALIDATION
#define PROBE_MANUALLY

folgendes deaktivert:

//#define FIX_MOUNTED_PROBE

Das sollte für MBL genügen. Hab mir 9 Punkte gemacht mit:

  #define MESH_INSET 10          // Set Mesh bounds as an inset region of the bed
  #define GRID_MAX_POINTS_X 3    // Don't use more than 7 points per axis, implementation limited.
  #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X

Kompiliert, geflasht, alles gut. Hab mir das TFT Menü angepasst mit G29 S1 für Start MBL und G29 S2 für den nächsten Punkt. Funktioniert alles soweit. Er startet das MBL, fährt alle 9 Punkte ab - alles perfekt soweit. Am Ende sag ich dann M500 für Save to EEPROM. Sagt er auch ok. Nur das Mesh ist und bleibt die ganze Zeit invalid. Wenn ich mir mit M501 die EEPROM lade seh ich kein Mesh, mit M503 (EEPROM anzeigen) auch keines und mit M420 S1 (Mesh Daten laden) wirft er dann natürlich nen Fehler, weil er n Mesh laden soll, dass er nicht hat bzw. ungültig ist. Kann mir wer sagen wo ich noch was vergessen habe im Code? Irgendwie wird das Mesh nicht gespeichert...

Danke für eure Hilfe und danke für die tolle Arbeit!

**Comment by Bodengriller** [comment]
Dein Vorhaben hat zwar nicht mehr viel mit dem hier angebotenem Mod zu tun, aber vielleicht hilft es dir weiter, wenn du dir mal die [3D-Nexus-Firmware](https://3d-nexus.com/resources/file-archives/download/5-printer-firmware/11-artillery-swx1-marlin-1-1-9-advanced-firmware-and-gui) anguckst (und ggf. mit deinem Umbau vergleichst).
Da ist MBL bereits aktiviert, funktioniert und ist von vielen Usern getestet und in Benutzung. (Ich nutze síe momentan tatsächlich auch).
Weiterhin gibt es von 3DN auch eine TFT-FW mit den nötigen MBL-Buttons.

Im Groben habe ich die 3DN-FW mal mit unserer hier vergleichend überflogen und keine gravierenden Unterschiede gefunden, die mir nicht komplett gegen den Strich gingen.

Folgende Unterschiede fielen mir beim Überfliegen auf:
1. Homing-Speed (3DN ist da ein bisschen schneller unterwegs...Geschmackssache)
2. Bed-Dimensionen (meiner Meinung nach sind die bei 3DN einfach falsch...man kann mit der Nozzle (minimal) über den Druckbereich hinten und rechts hinaus fahren...aber letztlich ist das auch Geschmacksache und tut der FW an sich keinen Abbruch - man überfährt keine mechanischen Endanschläge, kaputt kann man also nichts machen)
3. 3DN hat junction deviation nicht aktiviert (war bei 1.1.9 noch experimentell - sehen viele sogar als Vorteil an. Ich persönlich brauche es auch nicht)
4. Mesh-Bed-Leveling ist aktiviert (Wenn man es braucht -> großer Vorteil)
5. _Babystepping kann nicht gespeichert werden (Man müsste [als workaround] den Levelsensor aktivieren (fix mounted probe) um den Z-Offset im Eeprom speichern zu können - das steht sich m.W. aber mit MBL im Weg)_

**Bei Punkt 5 bin ich mir nicht zu 100% sicher!** - evtl klappt das Speichern des Z-Offsets auch, wenn MBL aktiviert ist. Ich habe da (noch) nicht weiter geforscht.

3DN läuft noch auf Marlin 1.1.9, was völlig OK ist - den Grund dafür erläutert man auf der 3DN-Seite: 1.1.9 ist als stable anzusehen und wird von SEHR vielen Leuten genutzt, ist daher ausgiebig erprobt.
Alles danach bringt ohnehin nur nennenswerte Vorteile für 32Bit-Boards und weist leider immer wieder neue Fehler(chen) auf...was auch der Grund dafür ist, wieso dieses Projekt hier ein wenig eingeschlafen ist.
Letzten Endes machen wir uns nur das Leben schwer, damit da die neuste Versionsnummer im Display steht und man hoffen kann, dass irgendeine neue Implementierung nicht irgendwas funktionierendes zerschossen hat.

**Comment by Hundsbuah** [comment]
Super danke dir für deine Antwort.
Die 3DN hab ich auch schon gesehe, aber mich hat die 1.1.9 abgeschreckt :)

Dann werde ich doch mal die von 3DN testen. Ich brauch MBL da mein Bed sehr, naja, krumm ist :/

Bei thingiverse gibts auch noch eine mit mbl und marlin 2, war aber damals nicht so zufrieden (lag aber vermutlich daran, dass die steps in der fw anders (falsch?) sind, was ich aber erst später gelesen habe: ( **80.121, 80.121, 399.778**, 485,28 (meine)) gegenüber der fw ( **80.121, 79.92, 399.778**, 409 ) - extruder steps sind klar das sie unterschiedlich sind.
https://www.thingiverse.com/thing:4043317


zu deinem 2. punkt, meinst du diese zeile im code?

// The size of the print bed
#define X_BED_SIZE 300
**#define Y_BED_SIZE 310**

Dann kompiliere ich die FW einfach nochmal neu, source ist bei 3dn ja dabei.

Danke nochmal für deine Antwort!

**Comment by Bodengriller** [comment]
Das mit den X/Y Steps ist auch so ne Sache.
Original von Artillery:
{ 80.121, 80.121, 399.778, 445 }
Viele (und auch 3DN) schwören auf:
{ 80, 80, 400, 445 }

Ich habe beides probiert und kann tatsächlich bei mir keine nennenswerten Unterschiede feststellen, darum blieben bei mir jetzt erstmal die 80.00 auf X und Y und 400 auf Z von 3DN drin - ich kann nicht klagen.

Zu Punkt 2 bezüglich der Bett-Dimensionen meine ich folgendes:
3DN:
```
// The size of the print bed
#define X_BED_SIZE 300
**#define Y_BED_SIZE 310**

// Travel limits (mm) after homing, corresponding to endstop positions.
**#define X_MIN_POS -2**
#define Y_MIN_POS -5
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 400
```

Wir haben ermittelt (und das passt bei mir nach wie vor besser):
```
// The size of the print bed
#define X_BED_SIZE 300
**#define Y_BED_SIZE 300**

// Travel limits (mm) after homing, corresponding to endstop positions.
**#define X_MIN_POS 0**
#define Y_MIN_POS -5
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 400
```

Ich habe aber gerade nochmal angefangen den Vergleich "unserer" und der 3DN Firmware genauer unter die Lupe zu nehmen.
Gib mir heute Abend nochmal Zeit, dann lade ich dir eine überarbeitet 3DN-Version hoch.

Eine Sache fiel mir tatsächlich gerade noch ins Auge -> die Max-Temperaturen...bei 260°C (PETG Temp-Tower) hab ich tatsächlich mächtiges Gezicke bei 3DN festgestellt... das liegt an der Max-Temperatur die dort auf 250 (-15 zur Sicherheit) begrenzt ist....das ist mir zu wenig und ist auch Unsinn (m.M.)

Ich melde mich hier, wenn ich soweit bin

**Comment by Bodengriller** [comment]
https://github.com/Bodengriller/3DN-ASWX1-FW-FoFi

Da habe ich mal alles dokumentiert, was **mir persönlich** ein (wenn auch winziger) Dorn im Auge war.
**Ich habe das noch nicht getestet!!!**
...kann mir aber auch nicht vorstellen, was nicht funktionieren sollte - sind alles nur marginale Änderungen.

Bisher ist alles, was in der Config geändert wurde, auch in der GitHub-Readme dokumentiert.
Weitere Änderungen sehe ich vorerst nicht kommen.

Möglich wären aber noch 2 Dinge, die mir einfallen:
1. Beim Babystepping bin ich mir ziemlich sicher, dass es (während des Drucks) mit der 3DN-FW nicht funktioniert und auch nicht gespeichert werden kann -> ich persönlich brauche das aber auch (noch?) nicht...ich level lieber nochmal und fange den Druck neu an - Falsch gelevelt geht sowieso meistens schief.
2. Ich hadere seit Langem mit mir, ob ich irgendwann einen BL-Touch nachrüste. Ich habe ihn hier liegen, aber irgendwas in mir weigert sich noch ihn zu benutzen.

Schöne Grüße

**Comment by Bodengriller** [comment]
Nur für die Vollständigkeit:
Bezüglich des Babysteppings kann ich nun eine konkrete Aussage treffen:
Man kann während des Druckes das Babystepping verstellen (Z+ und Z-) - das funktioniert auch.
Man kann diesen verstellten Wert jedoch nicht im EEPROM speichern.
Es gibt auch keine Möglichkeit oder Workaround fürs Speichern, wenn MBL aktiviert ist.

Näheres unter https://github.com/MarlinFirmware/Marlin/issues/3394

Der Button "Save to EEPROM" im Druck-Menü ist also irreführend oder überflüssig (bei der 3DN-TFT-FW).
