### ISSUE TITLE
[BUG] Overheat Protection dont stop heating

### ISSUE THREAD

**Issue by vVBladeVv** [pinguinpfleger/ASWX1-FW-MOD#17]
### Bug Description

Overheat Protection dont stop heating

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

i change only the driver settings for lv8729 

### Steps to Reproduce

1. [First Step]
i start the print job  and if heating i change some steps for leveling and store it on display 
the print job run with octoprint 
2. [Second Step]
i go to smoke .... 
3. [and so on...]
i come back and the printer smoke too 
**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

the printer heat the nozzle ( i think much over 300C° ) the tisplay show somethink with overheatprotection but i turn it off fast .
the extruder dont move and stop in the middle after first layer is printed but much to hot .
the extrude extrude filament and dont stop .  the heating rise and rise  and smoke  
the protection stop the moving but dont stop heating and extrude .

i clean the heatbrake  and have some demage on the bad  ( burn a hole )  the silikon socket is demage too .

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Bodengriller** [comment]
> the tisplay show somethink with overheatprotection

The software overtemperature shutdown seems to have worked very well, otherwise nothing would have been displayed.
Probably the power transistor of the cartridge heater on your mainboard is alloyed. 
If the hardware fails and switches through permanently, the software can still try to switch off as much as it can.
