### ISSUE TITLE
Enabling BLTouch

### ISSUE THREAD

**Issue by thierryzoller** [pinguinpfleger/ASWX1-FW-MOD#6]
I am unsure what to change in your version in order to enbale BLTouch support. Can you assist, or provide a pre-build version ?

**Comment by Bodengriller** [comment]
Waggster has BLTouch support in his Marlin-Builds:
https://pretendprusa.co.uk/index.php?action=downloads;cat=5

**Comment by thierryzoller** [comment]
Thanks Bodengriller, but I'd actually like to install your version and rely on i for future improvements. There is just an BLTOcuh env to uncomment ?

**Comment by Bodengriller** [comment]
activate BLTouch
define Probe-Pin
Set Probe-Offsets
choose a Bed Leveling, if you want to
activate Z-safe-homing

There are some things that need to be adjusted. But since we don't have or use BL-Touch, I can't give you any support at this point.
Maybe someone else can help you.
But the [Marlin documentation](https://marlinfw.org/docs/configuration/configuration.html) is very well structured and understandable - you are welcome to try it yourself.
Good luck :)

**Comment by thierryzoller** [comment]
Thank you very much. I will let you know of my outcome as to document it here.

**Comment by cadilu** [comment]
Hello all,

I´ve tried to enable BLTouch and something funny is happening:

BLTouch is un-commented and when issuing commands M280 P1 S10 and M280 P1 S90 the probe is deploying correctly. (And the servo number is correctly set as well in Marlin) Surprisingly, the probe doesn't respond to the G28 command (Fortunately I left the Z-min endstop and used the Zmax pin (19) for the probe. M119 shows the probe as triggered when stowed and open when deployed. I´m using a clone BLTouch probe.

Any idea of what could be done here?

Thank you very much in advance.

**Comment by Bodengriller** [comment]
Configuration.h

```
1182     *  If using a Probe for Z Homing, enable Z_SAFE_HOMING also!
```

```
1358    // With this feature enabled:
1359    //
1360    // - Allow Z homing only after X and Y homing AND stepper drivers still enabled.
1361    // - If stepper drivers time out, it will need X and Y homing again before Z homing.
1362    // - Move the Z probe (or nozzle) to a defined XY point before Z Homing when homing all axes (G28).
1363    // - Prevent Z homing when the Z probe is outside bed area.
1364    //
1365    //#define Z_SAFE_HOMING
```

src/inc/SanityCheck.h
```
1265    #if HOMING_Z_WITH_PROBE && IS_CARTESIAN && DISABLED(Z_SAFE_HOMING)
1266    //#error "Z_SAFE_HOMING is recommended when homing with a probe. Enable it or comment out this line to continue."
1267    #endif
```

Have you done that?
Probe-Offsets are set correctly?

**Comment by thierryzoller** [comment]
To answer my Issue : 

Official Guide to configure BLTouch in Marlin: 
https://5020dafe-17d8-4c4c-bf3b-914a8fdd5140.filesusr.com/ugd/f5a1c8_d40d077cf5c24918bd25b6524f649f11.pdf

```
 **Configuration.h**
//============================== Endstop Settings ===========================
#define USE_ZMIN_PLUG // a Z probe
#define ENDSTOPPULLUPS
#define ENDSTOP_INTERRUPTS_FEATURE

//============================= Z Probe Options =============================
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define BLTOUCH
#if ENABLED(BLTOUCH)
//#define BLTOUCH_DELAY 500 // *option
//#define BLTOUCH_FORCE_5V_MODE
#endif
#define PROBING_HEATERS_OFF // *option
#define PROBING_FANS_OFF // *option
#define X_PROBE_OFFSET_FROM_EXTRUDER 0 //Depend on your BLTouch installation value
#define Y_PROBE_OFFSET_FROM_EXTRUDER -22 //Depend on your BLTouch installation value
#define Z_PROBE_OFFSET_FROM_EXTRUDER -2.35 //Depend on your BLTouch installation value
//It must be greater than or equal to the higher of the X_PROBE_OFFSET_FROM_EXTRUDER and Y_PROBE_OFFSET_FROM_EXTRUDER.
#define MIN_PROBE_EDGE 22
#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z / 5
#define Z_CLEARANCE_DEPLOY_PROBE 15 // set up at least 10
#define Z_CLEARANCE_BETWEEN_PROBES 5 // set up at least 5
//=============================== Bed Leveling ==============================
#define AUTO_BED_LEVELING_BILINEAR // *option

```
**If you use the LED connector (Waggster) you need to also change RAMPS.h:**
```
//
#ifndef SERVO0_PIN
  #ifdef IS_RAMPS_13
    #define SERVO0_PIN      11
  #else
    #define SERVO0_PIN     11
  #endif
@ -102,10 +102,10 @@
#endif
#ifndef Z_STOP_PIN
  #ifndef Z_MIN_PIN
    #define Z_MIN_PIN      19
  #endif
  #ifndef Z_MAX_PIN
    #define Z_MAX_PIN      18
  #endif
#endif
```



@pinguinpfleger : How can I introduce these into your rep ? As an configuration_bltouch.h file?

**Comment by thierryzoller** [comment]
@pinguinpfleger : How can I introduce these into your rep ? As an configuration_bltouch.h file?

**Comment by pinguinpfleger** [comment]
well, I don't know that now either. I am not into BL-Touch and the changes that has to be made.
yeah maybe configuration_bltouch.h file with instructions or even a patch file could makes sense?

**Comment by cadilu** [comment]
> 
> 
> Configuration.h
> 
> ```
> 1182     *  If using a Probe for Z Homing, enable Z_SAFE_HOMING also!
> ```
> 
> ```
> 1358    // With this feature enabled:
> 1359    //
> 1360    // - Allow Z homing only after X and Y homing AND stepper drivers still enabled.
> 1361    // - If stepper drivers time out, it will need X and Y homing again before Z homing.
> 1362    // - Move the Z probe (or nozzle) to a defined XY point before Z Homing when homing all axes (G28).
> 1363    // - Prevent Z homing when the Z probe is outside bed area.
> 1364    //
> 1365    //#define Z_SAFE_HOMING
> ```
> 
> src/inc/SanityCheck.h
> 
> ```
> 1265    #if HOMING_Z_WITH_PROBE && IS_CARTESIAN && DISABLED(Z_SAFE_HOMING)
> 1266    //#error "Z_SAFE_HOMING is recommended when homing with a probe. Enable it or comment out this line to continue."
> 1267    #endif
> ```
> 
> Have you done that?
> Probe-Offsets are set correctly?

Yes, although unfortunately it didn't work. I tried with the Waggster distro as recommended in previous messages and that goth the thing working :)
