### ISSUE TITLE
Include Hemera Settings

### ISSUE THREAD

**Issue by Gamehunter1989** [pinguinpfleger/ASWX1-FW-MOD#8]
Ist es möglich eine Parallel Firmware zu erstellen, welche die Hemera Einstellungen beinhaltet?
Ich kenne mich mit Firmware leider nicht aus. Ich habe viel zu viel Respekt davor etwas zu ändern.

**Comment by Bodengriller** [comment]
Letztendlich müssen nur zwei Dateien angepasst werden:
Configuration.h
Configuration_adv.h

Ich denke nicht, dass man auf solche Sonderwünsche eingehen kann, schließlich hieße das auch einen erhöhten Pflegeaufwand für sämtliche Abspaltungen.
Es steht jedem frei sich seine configs nach seinem Belieben und seinen Vorstellungen anzupassen und zu probieren.
Du müsstest dich also kundig tun, was denn beim Hamera-Extruder anders als am originalen Extruder ist und dementsprechend einfach die paar Werte (viele können es m.E. nicht sein) in den hier zur Verfügung stehenden Configs ändern. Kein großes Thema.
Die Marlin-FW ist sehr gut dokumentiert und man findet überall ausreichend Informationen zu allen erdenklichen Fragestellungen.
Falls du keine Lust hast dich da einzulesen, müsstest du halt gucken, ob du irgendwo eine Marlin-Firmware bekommst, die irgendwer schon mal auf die groben SWX1-Parameter mit einem Hamera-Extruder eingeschossen hat

Beste Grüße


[EDIT]
Freundlicherweise stellen die Jungs von E3D sogar eine Schritt-für-Schritt Anleitung zur Verfügung: [Link](https://e3d-online.dozuki.com/Guide/Hemera+Artillery+(Evnovo)+Sidewinder+X1+Firmware+Modification/121?fbclid=IwAR2BITq4oZrkuaCNYb0VciskU4G2GWVfzusxQzLEnCxz8Fv-EvAqf_lkZS4)

**Comment by Armageddit** [comment]
mach es dir nicht zu kompliziert ;)
ich kenne die Übersetzung des Hemeras zwar nicht aber ich würde das einfach über die e-steps per G-Code ändern ;)
dann kannst du diese Firmware verwenden und musst nur einmal nach dem einspielen der neuen Firmware deine selbst erstellte Datei "Settings.gcode" laufen lassen und alles passt wieder
so mache ich das für meine Drucker und muss nicht lange irgendwas in der Configuration.h suchen und ersetzen ;)

**Comment by Bodengriller** [comment]
Das geht leider eben nicht so einfach, da nach der Hamera-Doku (Link oben) einiges mehr als nur die Steps geändert werden müssen:

```
#define TEMP_SENSOR_0 5
#define HEATER_0_MAXTEMP 300
#define THERMAL_PROTECTION_HOTENDS
#define DEFAULT_AXIS_STEPS_PER_UNIT { 80.121, 80.121, 399.778, 409 }
#define INVERT_E0_DIR true
```

Weder die Art des temperatursensors, noch die Maximal-Temperatur des Hotends, noch die Invertierung des Extruder-Steppers könnte er per gcode ändern.

Thermal Protection ist aktiv, E-Steps ließen sich über gcode ändern.

**Comment by discip** [comment]
@Bodengriller
Could you please tell me, what else than the *"Configuration.h"* and the *"Configuration_adv.h"* do I need to change, to be able to flash the sidewinder with a fresh Marlin "Nightly" Build.
e.g.: ***Marlin 2.1 development***

thank you in advance
